name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Heroku CLI available in the rest of the script
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Build and push
        run: ./api/deploy.sh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
